color0 #42474e
color1 #ffb4ab
color2 #a2caf7
color3 #b9c8db
color4 #e4b8ed
color5 #a2caf7
color6 #b9c8db
color7 #e2e2e6
color8 #8c9199
color9 #ffb4ab
color10 #a2caf7
color11 #b9c8db
color12 #e4b8ed
color13 #a2caf7
color14 #b9c8db
color15 #e2e2e6

cursor                #e2e2e6
cursor_text_color     #121316
background            #121316
foreground            #e2e2e6
selection_foreground  #c2c7cf
selection_background  #42474e
active_border_color   #a2caf7
inactive_border_color #42474e
url_color             #a2caf7

active_tab_foreground   #003355
active_tab_background   #a2caf7
inactive_tab_foreground #c2c7cf
inactive_tab_background #42474e
cursor_trail_color      #c2c7cf
