color0 #454842
color1 #ffb4ab
color2 #c3c8be
color3 #c6c7c2
color4 #c0c8ca
color5 #c3c8be
color6 #c6c7c2
color7 #e5e2e0
color8 #8f928b
color9 #ffb4ab
color10 #c3c8be
color11 #c6c7c2
color12 #c0c8ca
color13 #c3c8be
color14 #c6c7c2
color15 #e5e2e0

cursor                #e5e2e0
cursor_text_color     #131313
background            #131313
foreground            #e5e2e0
selection_foreground  #c5c7c0
selection_background  #454842
active_border_color   #c3c8be
inactive_border_color #454842
url_color             #c3c8be

active_tab_foreground   #2d322b
active_tab_background   #c3c8be
inactive_tab_foreground #c5c7c0
inactive_tab_background #454842
cursor_trail_color      #c5c7c0
