color0 #45474b
color1 #ffb4ab
color2 #c6c6cb
color3 #c7c6c8
color4 #cec4c9
color5 #c6c6cb
color6 #c7c6c8
color7 #e5e2e1
color8 #909095
color9 #ffb4ab
color10 #c6c6cb
color11 #c7c6c8
color12 #cec4c9
color13 #c6c6cb
color14 #c7c6c8
color15 #e5e2e1

cursor                #e5e2e1
cursor_text_color     #141313
background            #141313
foreground            #e5e2e1
selection_foreground  #c6c6cb
selection_background  #45474b
active_border_color   #c6c6cb
inactive_border_color #45474b
url_color             #c6c6cb

active_tab_foreground   #2e3035
active_tab_background   #c6c6cb
inactive_tab_foreground #c6c6cb
inactive_tab_background #45474b
cursor_trail_color      #c6c6cb
