color0 #45464c
color1 #ffb4ab
color2 #bfc6dc
color3 #c5c6cf
color4 #dbbed0
color5 #bfc6dc
color6 #c5c6cf
color7 #e5e2e3
color8 #909097
color9 #ffb4ab
color10 #bfc6dc
color11 #c5c6cf
color12 #dbbed0
color13 #bfc6dc
color14 #c5c6cf
color15 #e5e2e3

cursor                #e5e2e3
cursor_text_color     #131314
background            #131314
foreground            #e5e2e3
selection_foreground  #c6c6cd
selection_background  #45464c
active_border_color   #bfc6dc
inactive_border_color #45464c
url_color             #bfc6dc

active_tab_foreground   #293041
active_tab_background   #bfc6dc
inactive_tab_foreground #c6c6cd
inactive_tab_background #45464c
cursor_trail_color      #c6c6cd
